### ISSUE TITLE
帖子浏览的一个问题

### ISSUE THREAD

**Issue by drzzm32** [oxyflour/NyaSama#96]
在浏览单楼层长内容的帖子的时候进行拖动，整个layout的位置会在下一次点击屏幕的时候复位为初始位置，准确说是盛放帖子内容的那个TextView会在发生下一次拖动的点击时它的上边缘和标题栏下边缘对齐。

**Comment by oxyflour** [comment]
这个问题是由 https://github.com/NSDN/NyaSama/commit/44b53f0526065e0fa4b486dc0b9f41fef480f044 这个 commit 引入的。本来是针对 android 5 TextView 上的一个 bug 做的 hack
https://code.google.com/p/android/issues/detail?id=137509
看起来姿势不大对呢（咦

我看看周末能不能找个时间处理掉
